# https://github.com/commitizen-tools/commitizen-action/blob/673655ac2d9dbb1b6773c3b6191f78d9b3d2e4fa/.github/workflows/bumpversion.yaml
name: Bump version

# Allow for releases
on:
  push:
    branches:
      - main
      - staging

jobs:
  bump-version:
    if: ${{ !startsWith(github.event.head_commit.message, 'bump:') }}
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"

      - id: gpg
        name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          git_user_signingkey: true
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_commit_gpgsign: true
          git_tag_gpgsign: true
          git_push_gpgsign: true
          git_config_global: true
          trust_level: 5

      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          # Don't push immediately!
          push: false
          changelog_increment_filename: body.md
          git_redirect_stderr: true
          gpg_sign: false
          git_name: ${{ steps.gpg.outputs.name }}
          git_email: ${{ steps.gpg.outputs.email }}

      # Create a pull request to merge into staging
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: bump-version-${{ steps.cz.outputs.version }}
          title: Bump version ${{ steps.cz.outputs.version }}
          committer:
            "${{ steps.gpg.outputs.name }} ${{  steps.gpg.outputs.email }}"
      # add tag manually, since the PR action does not push tags
      - run: |
          git push origin --tags

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: "body.md"
          tag_name: ${{ steps.cz.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
